version: "3.7"
services:
  odl:
    build:
      context: ./odl
      dockerfile: Dockerfile
    image: frinx/fm-odl
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"    
    container_name: odl
    ports:
      - 8181:8181

  frinxit:
    build:
      context: ./frinxit
      dockerfile: Dockerfile
    image: frinx/fm-frinxit
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"    
    container_name: frinxit
    environment:
      - odl_target=odl
    ports:
      - 8888:8888

  micros:
    build:
      context: ./
      dockerfile: ./microservices/Dockerfile
    image: frinx/fm-micros
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    container_name: micros
    ports:
      - 6000:6000
    depends_on:
      - odl
      - conductor-server
    command: ["/home/app/wait_for_it.sh", "-t", "180",  "conductor-server:8080", "--", "python", "/home/app/netinfra_utils/workers/main.py"]

  sample-topology:
    build:
      context: ./
      dockerfile: ./sample-topology/Dockerfile
    image: frinx/fm-sample-topology
    container_name: sample-topology
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"

  conductor-server:
    build:
      context: ./conductor/
      dockerfile: docker/server/Dockerfile
    environment:
      - CONFIG_PROP=config.properties
    image: frinx/fm-conductor-server
    container_name: conductor-server
    links:
      - elasticsearch:es
      - dynomite:dyno1
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    ports:
      - 8080:8080
      - 8000:8000
    restart: on-failure
    depends_on:
      - dynomite
      - odl
    command: ["/app/wait_for.sh", "-t", "120",  "elasticsearch:9300", "--", "/app/startup.sh"]

  conductor-ui:
    build:
      context: ./conductor/
      dockerfile: docker/ui/Dockerfile
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: frinx/fm-conductor-ui
    container_name: conductor-ui
    links:
      - conductor-server
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    ports:
      - 5000:5000


  dynomite:
    build:
      context: ./
      dockerfile: ./dynomite/Dockerfile
    image: frinx/fm-dynomite
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    container_name: dynomite
    volumes:
       - redis_data:/var/lib/redis

  elasticsearch:
    build:
      context: ./
      dockerfile: ./elasticsearch/Dockerfile
    image: frinx/fm-elasticsearch
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
    volumes:
       - elastic_data:/usr/share/elasticsearch/data
    healthcheck:
        test: ["CMD", "curl", "-IGET", "http://localhost:9200"]
        interval: 2s
        timeout: 6s
        retries: 1

  kibana:
    build:
      context: ./kibana
      dockerfile: Dockerfile
    image: frinx/fm-kibana
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    container_name: kibana
    environment:
      - "elasticsearch.url=http://elasticsearch:9200"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  redis_data:
    name: redis_data
  elastic_data:
    name: elastic_data
