- pipeline.id: odl_logs
  path.config: "/usr/share/logstash/pipeline/karaf_logs.conf"
  pipeline.workers: 1
- pipeline.id: uniconfig_logs
  path.config: "/usr/share/logstash/pipeline/uniconfig_logs.conf"
  pipeline.workers: 1
- pipeline.id: controller_logs
  path.config: "/usr/share/logstash/pipeline/controller_logs.conf"
  pipeline.workers: 1
- pipeline.id: southbound_logs
  path.config: "/usr/share/logstash/pipeline/southbound_logs.conf"
  pipeline.workers: 1